name: "Build Commit"
on: push

jobs:
    build:
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-java@v4
              with:
                  distribution: temurin
                  java-version: 17

            - uses: gradle/actions/setup-gradle@v4
            - run: ./gradlew testGithubReleaseUnitTest
            - run: ./gradlew assembleGithubRelease

            - uses: actions/upload-artifact@v5
              with:
                  name: ReadYou-GitHub-Build-${{ github.sha }}
                  path: app/build/outputs/apk/github/release/*.apk
